// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPCStjMjxQ-nP0Qa-xJO72hb4USK_MoQ',
    appId: '1:116800525182:web:98e4cff98e8023b8b0192f',
    messagingSenderId: '116800525182',
    projectId: 'portfolioai-260e8',
    authDomain: 'portfolioai-260e8.firebaseapp.com',
    storageBucket: 'portfolioai-260e8.firebasestorage.app',
    measurementId: 'G-M481S17L16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCazJq2OXAFgFtRocoG1IaRvFGFjEUDlbk',
    appId: '1:116800525182:android:021c3b8c2f3ddbe7b0192f',
    messagingSenderId: '116800525182',
    projectId: 'portfolioai-260e8',
    storageBucket: 'portfolioai-260e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzgnK-SsyARqgrl6fLN7zOlS6zEO3zcUA',
    appId: '1:116800525182:ios:30015effd4ef1343b0192f',
    messagingSenderId: '116800525182',
    projectId: 'portfolioai-260e8',
    storageBucket: 'portfolioai-260e8.firebasestorage.app',
    androidClientId: '116800525182-p37vsq2oshjg28jmkn54uf1qevgl6755.apps.googleusercontent.com',
    iosClientId: '116800525182-8avo6gpan6a6dfq33oupihaupf4gg9jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzgnK-SsyARqgrl6fLN7zOlS6zEO3zcUA',
    appId: '1:116800525182:ios:30015effd4ef1343b0192f',
    messagingSenderId: '116800525182',
    projectId: 'portfolioai-260e8',
    storageBucket: 'portfolioai-260e8.firebasestorage.app',
    androidClientId: '116800525182-p37vsq2oshjg28jmkn54uf1qevgl6755.apps.googleusercontent.com',
    iosClientId: '116800525182-8avo6gpan6a6dfq33oupihaupf4gg9jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyPCStjMjxQ-nP0Qa-xJO72hb4USK_MoQ',
    appId: '1:116800525182:web:b7ea8ddafc3441bbb0192f',
    messagingSenderId: '116800525182',
    projectId: 'portfolioai-260e8',
    authDomain: 'portfolioai-260e8.firebaseapp.com',
    storageBucket: 'portfolioai-260e8.firebasestorage.app',
    measurementId: 'G-1PRVKXMH6F',
  );
}
